### ISSUE TITLE
How to configure new CSV database

### ISSUE THREAD

**Issue by Markenson** [Markenson/csv-metabase-driver#1]
Follow these instructions:

![image](https://user-images.githubusercontent.com/2985140/66673946-1d92e280-ec38-11e9-95fb-bddc25538c54.png)

**Comment by whintu** [comment]
Hello. I try to configure test connection to csv and get this message:
```
 java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
         at clojure.lang.MultiFn.getFn(MultiFn.java:156)
         at clojure.lang.MultiFn.invoke(MultiFn.java:233)
         at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:152)
         at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:147)
         at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:158)
         at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
         at metabase.driver.sql_jdbc$fn__71217.invokeStatic(sql_jdbc.clj:35)
         at metabase.driver.sql_jdbc$fn__71217.invoke(sql_jdbc.clj:34)
         at clojure.lang.MultiFn.invoke(MultiFn.java:234)
         at metabase.driver.util$can_connect_with_details_QMARK_$fn__22416.invoke(util.clj:32)
         at metabase.util$do_with_timeout$fn__9877.invoke(util.clj:302)
         at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
         at clojure.lang.AFn.call(AFn.java:18)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
 02-03 12:31:20 DEBUG middleware.log :: POST /api/database 400 13,0 ms (0 DB calls)
```

**Comment by vikashk77** [comment]
Hello, Markenson, 

Gives same error to me. Are we missing anything in the coonfiguration.

I replicated your steps though

Kind Regards,
Vikash

**Comment by Markenson** [comment]
> Hello. I try to configure test connection to csv and get this message:
> 
> ```
>  java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
>          at clojure.lang.MultiFn.getFn(MultiFn.java:156)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:233)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:152)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:147)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:158)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
>          at metabase.driver.sql_jdbc$fn__71217.invokeStatic(sql_jdbc.clj:35)
>          at metabase.driver.sql_jdbc$fn__71217.invoke(sql_jdbc.clj:34)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:234)
>          at metabase.driver.util$can_connect_with_details_QMARK_$fn__22416.invoke(util.clj:32)
>          at metabase.util$do_with_timeout$fn__9877.invoke(util.clj:302)
>          at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
>          at clojure.lang.AFn.call(AFn.java:18)
>          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>          at java.lang.Thread.run(Thread.java:748)
>  02-03 12:31:20 DEBUG middleware.log :: POST /api/database 400 13,0 ms (0 DB calls)
> ```



> Hello. I try to configure test connection to csv and get this message:
> 
> ```
>  java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
>          at clojure.lang.MultiFn.getFn(MultiFn.java:156)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:233)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:152)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:147)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:158)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
>          at metabase.driver.sql_jdbc$fn__71217.invokeStatic(sql_jdbc.clj:35)
>          at metabase.driver.sql_jdbc$fn__71217.invoke(sql_jdbc.clj:34)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:234)
>          at metabase.driver.util$can_connect_with_details_QMARK_$fn__22416.invoke(util.clj:32)
>          at metabase.util$do_with_timeout$fn__9877.invoke(util.clj:302)
>          at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
>          at clojure.lang.AFn.call(AFn.java:18)
>          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>          at java.lang.Thread.run(Thread.java:748)
>  02-03 12:31:20 DEBUG middleware.log :: POST /api/database 400 13,0 ms (0 DB calls)
> ```



> Hello. I try to configure test connection to csv and get this message:
> 
> ```
>  java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
>          at clojure.lang.MultiFn.getFn(MultiFn.java:156)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:233)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:152)
>          at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:147)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:158)
>          at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
>          at metabase.driver.sql_jdbc$fn__71217.invokeStatic(sql_jdbc.clj:35)
>          at metabase.driver.sql_jdbc$fn__71217.invoke(sql_jdbc.clj:34)
>          at clojure.lang.MultiFn.invoke(MultiFn.java:234)
>          at metabase.driver.util$can_connect_with_details_QMARK_$fn__22416.invoke(util.clj:32)
>          at metabase.util$do_with_timeout$fn__9877.invoke(util.clj:302)
>          at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
>          at clojure.lang.AFn.call(AFn.java:18)
>          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>          at java.lang.Thread.run(Thread.java:748)
>  02-03 12:31:20 DEBUG middleware.log :: POST /api/database 400 13,0 ms (0 DB calls)
> ```

Hi! I think this will solve the problem: https://github.com/Markenson/csv-metabase-driver/issues/2#issuecomment-608961918.

Cheers,
Markenson

**Comment by Markenson** [comment]
> Hello, Markenson,
> 
> Gives same error to me. Are we missing anything in the coonfiguration.
> 
> I replicated your steps though
> 
> Kind Regards,
> Vikash



> Hello, Markenson,
> 
> Gives same error to me. Are we missing anything in the coonfiguration.
> 
> I replicated your steps though
> 
> Kind Regards,
> Vikash


Hi! I think this will solve the problem: https://github.com/Markenson/csv-metabase-driver/issues/2#issuecomment-608961918.

Cheers,
Markenson

**Comment by theauheral** [comment]
Am I doing anything wrong? I tried directory, file... etc. I have the error 
I am using metabase v0.35.3 (Latest) and your latest csv driver.
Dataset: https://www.kaggle.com/doaaalsenani/usa-cers-dataset

Error: No suitable driver found for jdbc:relique:csv:file:/C:/Users/theau/Downloads/usa-cers-dataset/USA_cars_datasets.csv?separator=,&charset=utf-8


![screenshot csv metabase](https://user-images.githubusercontent.com/43614647/81242977-68c27780-9006-11ea-8ddf-216af0ab8d89.PNG)


[Logs CSV driver.txt.txt](https://github.com/Markenson/csv-metabase-driver/files/4590149/Logs.CSV.driver.txt.txt)

**Comment by Cooperllli-tech** [comment]
Hello, Markenson,

i'm still having this error: "No method in multimethod 'connection-details->spec' for dispatch value: :csv" with the latest version of metabase
i've follow the steps in your video but it didn't work

Kind Regards,
cooper
