### ISSUE TITLE
Limited Summarize Options

### ISSUE THREAD

**Issue by zeehasham** [Markenson/csv-metabase-driver#11]
When I import csv data, I do not see Sum of, Average, Min, Max etc. in Summarize options. Only Count and Cumulative Count is available. Any idea how we can get all the Summarize Options using this csv import?

**Comment by Markenson** [comment]
Try to change metadata column type at administrator menu.

Ref: https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html

**Comment by Markenson** [comment]
You could try to use columnTypes. Check https://github.com/Markenson/csv-metabase-driver/issues/13

**Comment by Markenson** [comment]
Please check this video to see csv driver with numeric options.

https://youtu.be/pMiIXPaelyg
