### ISSUE TITLE
reloading/updating csv source data

### ISSUE THREAD

**Issue by cyphunk** [Markenson/csv-metabase-driver#12]
Thank for this very useful plugin. 

Is it possible to update the csv data automatically? Curious of two conditions:

1. If I add a new csv file to the watched csv directory for a db that is based on this plugin, will that file be automatically read?
2. If I update an existing csv file that was already successfully read by the plugin, will the data show in metabase be automatically read anew?

**Comment by Markenson** [comment]
Hi @cyphunk !

The answer about questions 1 and 2 is "yes", but updates aren't a plugin feature. It depends on metabase sync instead plugins. Check [this](https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis) for details. To force updates click on "Sync database schema now" and "Re-scan field values now" buttons (I always click on "Discard saved field values" but I don't have certain about need this.)

Regards!
