### ISSUE TITLE
Tip: do not use quotes in the fields for Separator, Charset, and Advanced

### ISSUE THREAD

**Issue by rogererens** [Markenson/csv-metabase-driver#13]
I have this patient.csv file:
'''
patient_id;patient_name;dob;room_id
1001;Alice;31-12-2000;05
2002;Bob;01-10-1999;02
3333;Chris;17-05-1988;03
'''
which I try to load with these values in the fields Separator, Charset, and Advanced resp.:
;
utf-8
&columnTypes="Integer,String,Date,Integer"&dateFormat="dd-MM-yyyy"

The admin dashboard of Metabase shows at
http://localhost:3000/admin/datamodel/database/<some-db-id>
that there are zero schemas in this database.

When I load patient.csv without the Advanced value set, Metabase reports that the database has 1 queriable table, consisting of 4 columns of non-specific type.

Am I missing something in the syntax to be used for the &columnTypes and &dateFormat values?

**Comment by rogererens** [comment]
I found that the value in the Advanced field should be quoteless:
&columnTypes=Integer,String,Date,Integer&dateFormat=dd-MM-yyyy

results in Metabase showing a table in this database.

**Comment by Markenson** [comment]
Hi @rogererens !

Thanks for your tip.

That's all ok, right? Then I'll close this issue.

Regards
