### ISSUE TITLE
Failed when adding new db

### ISSUE THREAD

**Issue by dl-lim** [Markenson/csv-metabase-driver#19]
Hey, thanks for this amazing tool, btw! This should be in the default metabase for sure! :)

I'm getting this error:
`No method in multimethod 'connection-details->spec' for dispatch value: :csv`

![image](https://user-images.githubusercontent.com/69715968/109289925-e2f80d00-7861-11eb-88ca-413e50e2b76e.png)

I tried with my filename inside, tz.csv, and even without it. 
CSV was compiled from Excel, if it makes a difference...

And the only place I see this being mentioned is in #1 and was due to version updates, it seems #2 

My current metabase (pulled from docker metabase/metabase):
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-65-generic",
    "user.language": "en",
    "user.timezone": "America/Buenos_Aires"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.0 (Debian 13.0-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-02-16",
      "tag": "v0.38.0",
      "branch": "release-x.38.x",
      "hash": "471aa51"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
Could my version be too new?

**Comment by alderson59** [comment]
So I tried saving again with UTF-8, using notepad. Still the same problem. Perhaps a version update problem?

**Comment by Markenson** [comment]
Hi! @alderson59 

Could you send the error logs, please? (Troubleshoot menu on administrative panel)

**Comment by Markenson** [comment]
I can't reproduce the error. I've recorded video below with latest version of metabase (0.43.4) today and it worked for me. Please try to reproduce the video steps and check if there are some difference between I did and what you doing.

Best Regards!

https://youtu.be/M4ccnTXiDtw
