### ISSUE TITLE
Cant Load CSV 

### ISSUE THREAD

**Issue by tcl1990** [Markenson/csv-metabase-driver#2]
Trying it at the Metabase version v0.34.0.
Unable to load the .csv files.
Details as below.

![image](https://user-images.githubusercontent.com/59133586/71318803-c4192080-24d0-11ea-908b-277a6672f09d.png)
![image](https://user-images.githubusercontent.com/59133586/71318804-c7141100-24d0-11ea-9f68-185e7610c8a0.png)

**Comment by Markenson** [comment]
Can you post your sample csv file?

**Comment by Markenson** [comment]
I'd tested it on 0.32.0 and it was works ok. Could be some different thing on 0.34.0. I'll try check this.

**Comment by willhseitz** [comment]
I can also confirm that this works on 0.32.10, but not on 0.34.1

**Comment by ctmay4** [comment]
Currently having the same issue.  Something change in 0.34+.

**Comment by Markenson** [comment]
I fixed the issue and now it works on 0.35.1 version. Please download it again from [initial page](https://github.com/Markenson/csv-metabase-driver).

**Comment by ctmay4** [comment]
Verified working.  Thanks!
