### ISSUE TITLE
Can't filter by timestamp 

### ISSUE THREAD

**Issue by dominikbrazdil** [Markenson/csv-metabase-driver#21]
I successfully imported a CSV as a dataset and everything works fine. The thing is that one column is ISO 8601 timestamp which gets correctly parsed in metabase after I set the column type to 'Creation timestamp'. The problem is that whenever I try to filter the data by this timestamp some error pops up. Once it's 
`"No method in multimethod 'add-interval-honeysql-form' for dispatch value: :csv"`
or 
`SQL function not found: NOW`
This works fine for other types of databases so I'm convinced that the issue is in this driver.
I'm running metabase v0.38.1

Here is the log:
`{:via
 [{:type java.lang.IllegalArgumentException,
   :message "No method in multimethod 'add-interval-honeysql-form' for dispatch value: :csv",
   :at [clojure.lang.MultiFn getFn "MultiFn.java" 156]}],
 :trace
 [[clojure.lang.MultiFn getFn "MultiFn.java" 156]
  [clojure.lang.MultiFn invoke "MultiFn.java" 243]
  [metabase.driver.sql.query_processor$fn__41369 invokeStatic "query_processor.clj" 539]
  [metabase.driver.sql.query_processor$fn__41369 invoke "query_processor.clj" 535]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.driver.sql.query_processor$fn__41533 invokeStatic "query_processor.clj" 656]
  [metabase.driver.sql.query_processor$fn__41533 invoke "query_processor.clj" 654]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.driver.sql.query_processor$fn__41615 invokeStatic "query_processor.clj" 713]
  [metabase.driver.sql.query_processor$fn__41615 invoke "query_processor.clj" 711]
  [clojure.lang.MultiFn invoke "MultiFn.java" 244]
  [metabase.driver.sql.query_processor$apply_top_level_clauses$fn__41721 invoke "query_processor.clj" 877]
  [clojure.lang.ArraySeq reduce "ArraySeq.java" 116]
  [clojure.core$reduce invokeStatic "core.clj" 6827]
  [clojure.core$reduce invoke "core.clj" 6810]
  [metabase.driver.sql.query_processor$apply_top_level_clauses invokeStatic "query_processor.clj" 875]
  [metabase.driver.sql.query_processor$apply_top_level_clauses invoke "query_processor.clj" 871]
  [metabase.driver.sql.query_processor$apply_clauses invokeStatic "query_processor.clj" 927]
  [metabase.driver.sql.query_processor$apply_clauses invoke "query_processor.clj" 917]
  [metabase.driver.sql.query_processor$mbql__GT_honeysql invokeStatic "query_processor.clj" 953]
  [metabase.driver.sql.query_processor$mbql__GT_honeysql invoke "query_processor.clj" 950]
  [metabase.driver.sql.query_processor$mbql__GT_native invokeStatic "query_processor.clj" 964]
  [metabase.driver.sql.query_processor$mbql__GT_native invoke "query_processor.clj" 961]
  [metabase.driver.sql$fn__79075 invokeStatic "sql.clj" 38]
  [metabase.driver.sql$fn__79075 invoke "sql.clj" 36]
  [clojure.lang.MultiFn invoke "MultiFn.java" 234]
  [metabase.query_processor.middleware.mbql_to_native$query__GT_native_form invokeStatic "mbql_to_native.clj" 14]
  [metabase.query_processor.middleware.mbql_to_native$query__GT_native_form invoke "mbql_to_native.clj" 9]
  [metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46414 invoke "mbql_to_native.clj" 22]
  [metabase.query_processor.middleware.check_features$check_features$fn__45666 invoke "check_features.clj" 41]
  [metabase.query_processor.middleware.limit$limit$fn__46400 invoke "limit.clj" 37]
  [metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45324 invoke "cache.clj" 211]
  [metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46579
   invoke
   "optimize_datetime_filters.clj"
   133]
  [metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44470
   invoke
   "auto_parse_filter_values.clj"
   43]
  [metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40787
   invoke
   "wrap_value_literals.clj"
   147]
  [metabase.query_processor.middleware.annotate$add_column_info$fn__40650 invoke "annotate.clj" 582]
  [metabase.query_processor.middleware.permissions$check_query_permissions$fn__45541 invoke "permissions.clj" 75]
  [metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47102
   invoke
   "pre_alias_aggregations.clj"
   40]
  [metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45739
   invoke
   "cumulative_aggregations.clj"
   60]
  [metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47415
   invoke
   "resolve_joined_fields.clj"
   94]
  [metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__47720 invoke "resolve_joins.clj" 178]
  [metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44064
   invoke
   "add_implicit_joins.clj"
   181]
  [metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__46375 invoke "large_int_id.clj" 44]
  [metabase.query_processor.middleware.format_rows$format_rows$fn__46355 invoke "format_rows.clj" 74]
  [metabase.query_processor.middleware.desugar$desugar$fn__45805 invoke "desugar.clj" 21]
  [metabase.query_processor.middleware.binning$update_binning_strategy$fn__44830 invoke "binning.clj" 228]
  [metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45348 invoke "resolve_fields.clj" 24]
  [metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__43694
   invoke
   "add_dimension_projections.clj"
   316]
  [metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43925
   invoke
   "add_implicit_clauses.clj"
   146]
  [metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48150
   invoke
   "upgrade_field_literals.clj"
   45]
  [metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44217
   invoke
   "add_source_metadata.clj"
   122]
  [metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47299
   invoke
   "reconcile_breakout_and_order_by_bucketing.clj"
   97]
  [metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44417
   invoke
   "auto_bucket_datetimes.clj"
   139]
  [metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45395
   invoke
   "resolve_source_table.clj"
   45]
  [metabase.query_processor.middleware.parameters$substitute_parameters$fn__47084 invoke "parameters.clj" 111]
  [metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45447
   invoke
   "resolve_referenced.clj"
   79]
  [metabase.query_processor.middleware.expand_macros$expand_macros$fn__46061 invoke "expand_macros.clj" 155]
  [metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44226 invoke "add_timezone_info.clj" 15]
  [metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48086
   invoke
   "splice_params_in_response.clj"
   32]
  [metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47310$fn__47314
   invoke
   "resolve_database_and_driver.clj"
   31]
  [metabase.driver$do_with_driver invokeStatic "driver.clj" 60]
  [metabase.driver$do_with_driver invoke "driver.clj" 56]
  [metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47310
   invoke
   "resolve_database_and_driver.clj"
   25]
  [metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46301
   invoke
   "fetch_source_query.clj"
   274]
  [metabase.query_processor.middleware.store$initialize_store$fn__48095$fn__48096 invoke "store.clj" 11]
  [metabase.query_processor.store$do_with_store invokeStatic "store.clj" 44]
  [metabase.query_processor.store$do_with_store invoke "store.clj" 38]
  [metabase.query_processor.middleware.store$initialize_store$fn__48095 invoke "store.clj" 10]
  [metabase.query_processor.middleware.validate$validate_query$fn__48157 invoke "validate.clj" 10]
  [metabase.query_processor.middleware.normalize_query$normalize$fn__46427 invoke "normalize_query.clj" 22]
  [metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44082
   invoke
   "add_rows_truncated.clj"
   35]
  [metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48071
   invoke
   "results_metadata.clj"
   147]
  [metabase.query_processor.reducible$async_qp$qp_STAR___37428$thunk__37429 invoke "reducible.clj" 103]
  [metabase.query_processor.reducible$async_qp$qp_STAR___37428 invoke "reducible.clj" 109]
  [metabase.query_processor.reducible$sync_qp$qp_STAR___37437$fn__37440 invoke "reducible.clj" 135]
  [metabase.query_processor.reducible$sync_qp$qp_STAR___37437 invoke "reducible.clj" 134]
  [metabase.query_processor$preprocess_query invokeStatic "query_processor.clj" 164]
  [metabase.query_processor$preprocess_query invoke "query_processor.clj" 156]
  [metabase.query_processor$query__GT_native invokeStatic "query_processor.clj" 193]
  [metabase.query_processor$query__GT_native invoke "query_processor.clj" 189]
  [metabase.query_processor$query__GT_native_with_spliced_params invokeStatic "query_processor.clj" 206]
  [metabase.query_processor$query__GT_native_with_spliced_params invoke "query_processor.clj" 197]
  [metabase.api.dataset$fn__54407 invokeStatic "dataset.clj" 126]
  [metabase.api.dataset$fn__54407 invoke "dataset.clj" 122]
  [compojure.core$wrap_response$fn__1993 invoke "core.clj" 160]
  [compojure.core$wrap_route_middleware$fn__1977 invoke "core.clj" 132]
  [compojure.core$wrap_route_info$fn__1982 invoke "core.clj" 139]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 151]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 152]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.server.middleware.auth$enforce_authentication$fn__73836 invoke "auth.clj" 14]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 297]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.api.routes$fn__73957$fn__73959 invoke "routes.clj" 69]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [metabase.server.routes$fn__76139$fn__76140 doInvoke "routes.clj" 57]
  [clojure.lang.RestFn invoke "RestFn.java" 436]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [compojure.core$make_context$handler__2033 invoke "core.clj" 287]
  [compojure.core$make_context$fn__2035 invoke "core.clj" 296]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [compojure.core$wrap_route_matches$fn__1986 invoke "core.clj" 153]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007 invoke "core.clj" 197]
  [metabase.server.routes$fn__76127$fn__76129 invoke "routes.clj" 41]
  [compojure.core$routes$fn__2005$f__2006 invoke "core.clj" 198]
  [compojure.core$routes$fn__2005 invoke "core.clj" 200]
  [metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73948 invoke "exceptions.clj" 96]
  [metabase.server.middleware.exceptions$catch_api_exceptions$fn__73945 invoke "exceptions.clj" 84]
  [metabase.server.middleware.log$log_api_call$fn__76055$fn__76056 invoke "log.clj" 195]
  [toucan.db$_do_with_call_counting invokeStatic "db.clj" 216]
  [toucan.db$_do_with_call_counting invoke "db.clj" 209]
  [metabase.server.middleware.log$log_api_call$fn__76055 invoke "log.clj" 189]
  [metabase.server.middleware.security$add_security_headers$fn__73911 invoke "security.clj" 142]
  [metabase.server.middleware.json$wrap_json_body$fn__75836 invoke "json.clj" 62]
  [metabase.server.middleware.json$wrap_streamed_json_response$fn__75854 invoke "json.clj" 98]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__76396 invoke "keyword_params.clj" 55]
  [ring.middleware.params$wrap_params$fn__76412 invoke "params.clj" 69]
  [metabase.server.middleware.misc$maybe_set_site_url$fn__35081 invoke "misc.clj" 58]
  [metabase.server.middleware.session$bind_current_user$fn__41914$fn__41915 invoke "session.clj" 277]
  [metabase.server.middleware.session$do_with_current_user invokeStatic "session.clj" 258]
  [metabase.server.middleware.session$do_with_current_user invoke "session.clj" 250]
  [metabase.server.middleware.session$bind_current_user$fn__41914 invoke "session.clj" 276]
  [metabase.server.middleware.session$wrap_current_user_info$fn__41901 invoke "session.clj" 236]
  [metabase.server.middleware.session$wrap_session_id$fn__41887 invoke "session.clj" 182]
  [metabase.server.middleware.auth$wrap_api_key$fn__73844 invoke "auth.clj" 27]
  [ring.middleware.cookies$wrap_cookies$fn__76316 invoke "cookies.clj" 216]
  [metabase.server.middleware.misc$add_content_type$fn__35064 invoke "misc.clj" 27]
  [metabase.server.middleware.misc$disable_streaming_buffering$fn__35089 invoke "misc.clj" 75]
  [ring.middleware.gzip$wrap_gzip$fn__76358 invoke "gzip.clj" 86]
  [metabase.server.middleware.misc$bind_request$fn__35092 invoke "misc.clj" 92]
  [metabase.server.middleware.ssl$redirect_to_https_middleware$fn__76072 invoke "ssl.clj" 38]
  [metabase.server$async_proxy_handler$fn__75669 invoke "server.clj" 71]
  [metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 127]
  [org.eclipse.jetty.server.Server handle "Server.java" 516]
  [org.eclipse.jetty.server.HttpChannel lambda$handle$1 "HttpChannel.java" 383]
  [org.eclipse.jetty.server.HttpChannel dispatch "HttpChannel.java" 556]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 375]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 273]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 311]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 105]
  [org.eclipse.jetty.io.ChannelEndPoint$1 run "ChannelEndPoint.java" 104]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill runTask "EatWhatYouKill.java" 336]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill doProduce "EatWhatYouKill.java" 313]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill tryProduce "EatWhatYouKill.java" 171]
  [org.eclipse.jetty.util.thread.strategy.EatWhatYouKill run "EatWhatYouKill.java" 129]
  [org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread run "ReservedThreadExecutor.java" 375]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 773]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 905]
  [java.lang.Thread run "Thread.java" 834]],
 :cause "No method in multimethod 'add-interval-honeysql-form' for dispatch value: :csv",
 :message "No method in multimethod 'add-interval-honeysql-form' for dispatch value: :csv",
 :type java.lang.IllegalArgumentException}`

**Comment by Markenson** [comment]
Hi! 
Sorry... My time is tight, but I will try to look into this issue if possible.

Please put your csv file here. Maybe someone can help us

**Comment by dominikbrazdil** [comment]
Sure, totally understand. Here is my csv file:
[data.csv](https://github.com/Markenson/csv-metabase-driver/files/6708818/data.csv)

**Comment by Markenson** [comment]
You need config your time field. Please check this video for reference: https://youtu.be/qrTux2jIwns

![image](https://user-images.githubusercontent.com/2985140/180316619-b26f13d7-b868-49b1-b090-e6e535b959c2.png)
