### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by zeehasham** [Markenson/csv-metabase-driver#23]
I am getting EOF error while importing csv file.

Syntax error: Encountered " <NAME> "\"parent_address_key\" "" at line 2, column 38. Was expecting: <EOF>

where parent_address_key is the first column in my csv file.

**Comment by sudo-ahmedreda** [comment]
getting the same error, any update please?

**Comment by Markenson** [comment]
Hi everyone! 
Sorry... My time is tight, but I will try to look into this issue if possible.

Put your csv file here. Maybe someone can help you too

**Comment by sudo-ahmedreda** [comment]
Thanks Markenson for your reply! all the CSV file I have tried give the same attached is a sample file
[text.ZIP](https://github.com/Markenson/csv-metabase-driver/files/6709870/text.ZIP)
error #

**Comment by oamm** [comment]
Hi @Markenson !
i have the same issue but i want to know how i can help you to fix it? 

`Syntax error: Encountered " <NAME> "\"ESTADO\" "" at line 2, column 63. Was expecting: <EOF>`

**Comment by olivercrask** [comment]
Same issue here! Issue did not occur in 0.38 but when updating to 0.4 it started

`Syntax error: Encountered \" <NAME> \"\\\"Year\\\" \"\" at line 2, column 38.\nWas expecting:\n    <EOF> \n    `

**Comment by pigipi** [comment]
Hey, I have the same problem with my CSV files. 
Someone find a way to resolve it? 

_Syntax error: Encountered " <NAME> "\"Date\" "" at line 2, column 29. Was expecting: <EOF>_

**Comment by Markenson** [comment]
Hi all!

Please try to use [thw new 1.2.0 version](https://github.com/Markenson/csv-metabase-driver/releases/download/1.2.0/csv.metabase-driver.jar) to solve EOF error.
