### ISSUE TITLE
Unable to start Metabase after install

### ISSUE THREAD

**Issue by doylegrant** [Markenson/csv-metabase-driver#24]
Every time I place the csv.metabase-driver.jar file in the plugins folder and restart, Metabase crashes while starting. 

Metabase version v0.39.4 (f538050 release-x.39.x)
Java Version 11.0.11

error:
> 2021-07-15 23:11:52,736 INFO metabase.plugins :: Loading plugins in /plugins...
2021-07-15 23:11:53,155 ERROR metabase.core :: Metabase Initialization FAILED
java.util.zip.ZipException: zip END header not found

I'm using curl to download the file directly to the Plugins folder from Bash inside the Docker container. Could this be the issue?

**Comment by Markenson** [comment]
Hi!

I think is related to download process or file permission after download. A good test is download It manually and  check if error still occours.

**Comment by Markenson** [comment]
I can't reproduce the error. I've recorded video below with latest version of metabase (0.43.4) today and it worked for me. Please try to reproduce the video steps and check if there are some difference between I did and what you doing.

Best Regards!

https://youtu.be/M4ccnTXiDtw
