### ISSUE TITLE
I keep getting Directory not found

### ISSUE THREAD

**Issue by BryanNah** [Markenson/csv-metabase-driver#25]
Hello everyone, I keep getting directory not found. 
Is it because am running Metabase version 0.40 the latest. 
Please help...
![metabase_ui](https://user-images.githubusercontent.com/11467272/128348601-a55710e3-eac9-451b-91b3-59252017e892.PNG)
![metabase_back](https://user-images.githubusercontent.com/11467272/128348623-fe28c487-ff85-44b7-9037-dc0afa64a8e7.PNG)

**Comment by Markenson** [comment]
Hi @BryanNah !

If you are using windows, try to use "D:\Metabase_project\[your path]\".

If your files are in a mounted directory, check if your access permissions are ok.

![image](https://user-images.githubusercontent.com/2985140/128352957-e77b5439-ad6c-446f-9450-a61a57f52801.png)

Regards

**Comment by Markenson** [comment]
You could try to use [the new 1.3.1 version](https://github.com/Markenson/csv-metabase-driver/releases/download/v1.3.1/csv.metabase-driver.jar) too...

**Comment by BryanNah** [comment]
Thank you, It works fine
