### ISSUE TITLE
No tables after adding a CSV file

### ISSUE THREAD

**Issue by akkisagiraju** [Markenson/csv-metabase-driver#26]
Hello,

After adding a CSV file via HTTPS as a DB, if I try to open it, Metabase says "This database doesn't have any tables."
 
![Screenshot 2021-09-03 at 13-25-32 Databases · Admin · Metabase](https://user-images.githubusercontent.com/7601150/131971700-edd0eb6d-dd55-4ce0-a31a-99c08ec816b9.png)

![Screenshot 2021-09-03 at 13-26-00 Metabase](https://user-images.githubusercontent.com/7601150/131971669-c2d2ae69-0493-4e61-a8b2-9b57149b9487.png)

I also tried defining customTables in the Advanced field while adding the CSV file but that too didn't solve the problem. This is how data is inside the CSV file I'm trying to add.

```
SubmissionDate,zone,age,meta-instanceID,KEY,SubmitterID,SubmitterName,AttachmentsPresent,AttachmentsExpected,Status,ReviewState,DeviceID,Edits
2021-08-30T15:34:49.292Z,Edinburgh,47,uuid:ad0a36f8-0ba8-4bab-8a0d-5b7eb1888f58,uuid:ad0a36f8-0ba8-4bab-8a0d-5b7eb1888f58,5,education@noral.com,0,0
2021-08-30T15:34:42.729Z,Edinburgh,47,uuid:9193e949-9e0d-4db2-9cac-9605d6d360cb,uuid:9193e949-9e0d-4db2-9cac-9605d6d360cb,5,education@noral.com,0,0
```

Could this be an issue or am I doing something wrong?

**Comment by Markenson** [comment]
I've recorded video below with latest version of metabase (0.43.4) today and it worked for me. Please try to reproduce the video steps and check if there are some difference between I did and what you doing.

Best Regards!

https://youtu.be/M4ccnTXiDtw
