### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by juliejulie777** [Markenson/csv-metabase-driver#27]
Hi there. 

I tried to connect the csv driver to the latest metabase in mac. However, I keep getting the same error msg: Directory not found. Can anyone share some light on this? 

Here is the set up: 

<img width="666" alt="Screenshot 2022-05-16 at 1 02 54 PM" src="https://user-images.githubusercontent.com/105623066/168523254-8fc060bc-a4cb-4701-8c72-5153db29998f.png">

Here is the error log:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/105623066/168523329-d85ab149-3602-4215-89bf-a1b9b2bc07ac.png">

Thank you!

**Comment by tomasmserra** [comment]
Hi , you are solution it?

**Comment by Markenson** [comment]
Hi all!

You tried add a slash at end of path ou check read permissions?
Are you runiing metabase from a docker container? Maybe this path couldn't be acessible and require some additional volume configuration.

**Comment by Markenson** [comment]
I've recorded video below with latest version of metabase (0.43.4) today and it worked for me. Please try to reproduce the video steps and check if there are some difference between I did and what you doing.

Best Regards!

https://youtu.be/M4ccnTXiDtw

**Comment by willywildan** [comment]
how to fixed it? @Markenson 
![image](https://user-images.githubusercontent.com/40651953/206961329-cdf7ed33-764b-441a-8020-3348d8dfbf6d.png)

**Comment by Markenson** [comment]
Hi @willywildan !
The message "This a community-driver..." is a warning only. Try to follow steps above and see if you get some error message.

**Comment by willywildan** [comment]
Thankyou @Markenson  i've fixed it, how maximum size of csv file on this plugin?
