### ISSUE TITLE
CSV won't be read by metabase if there's empty column header

### ISSUE THREAD

**Issue by tjiahen** [Markenson/csv-metabase-driver#29]
### Reproduce steps:

1. use this settings on metabase

![image](https://user-images.githubusercontent.com/462417/182284826-1683aa05-41ce-4e4c-9578-e758e2bec48d.png)

2. added these csv to the directory

working.csv

```
ID,Email,batch,favorite
3,example@example.com,1,TRUE
```

not_working.csv

```
ID,Email,,,batch,favorite
3,example@example.com,,,1,TRUE
```

3. metabase will only load the working.csv

**Comment by tjiahen** [comment]
It is a csvjsdb thing? https://stackoverflow.com/questions/43864204/reading-csv-file-without-header-with-csv-jdbc-driver

seems like I could just add the ```suppressHeaders ``` in advance textfield?

**Comment by Markenson** [comment]
Please add the following in advanced configuration:

`&suppressHeaders=true`

Or 

`&defectiveHeaders=true`

Like this

![image](https://user-images.githubusercontent.com/2985140/182634434-094ce8a3-023d-4246-8af9-b30e91412145.png)


The result using [without_header.csv](https://github.com/Markenson/csv-metabase-driver/files/9252360/without_header.csv) file is 

![image](https://user-images.githubusercontent.com/2985140/182636034-0cae165b-b439-49db-b8d9-e5d7a0702d6e.png)

![image](https://user-images.githubusercontent.com/2985140/182635625-e32dc364-de37-447c-83b1-2293d37dde54.png)
