### ISSUE TITLE
Error on Date Filtering

### ISSUE THREAD

**Issue by tcl1990** [Markenson/csv-metabase-driver#4]
Hi!
I'm loading the data from the .csv file and filtering via date time, below error shown..

![image](https://user-images.githubusercontent.com/59133586/80469282-eb966300-8972-11ea-9618-f0bc98411cdb.png)

**Comment by tcl1990** [comment]
Many thanks for your time and all your good work :)

**Comment by Markenson** [comment]
Can you post a csv sample file?

**Comment by Markenson** [comment]
You need config date. Please check this video https://youtu.be/qrTux2jIwns
