### ISSUE TITLE
Issue with latest Metabase 0.37.2 community edition

### ISSUE THREAD

**Issue by hireninnodel** [Markenson/csv-metabase-driver#6]
We had 0.36.7 metabase on centos 7 and this CSV plugin was working fine. Today we upgraded metabase to 0.37.2 and kept the same database. With 0.37.2 CSV option comes in databases link but am able to create CSV database source but, when trying to explore it keep loading and nothing happens. Can this be fixed as soon as possible?

**Comment by Markenson** [comment]
Could you post a csv sample file and md5 of your csv.jar driver file?

**Comment by hireninnodel** [comment]
> Could you post a csv sample file and md5 of your csv.jar driver file?

[Sample.zip](https://github.com/Markenson/csv-metabase-driver/files/5672440/Sample.zip)

Kindly download the Sample.zip and look at my csv upload issue in metabase.

**Comment by hireninnodel** [comment]
[Sample.zip](https://github.com/Markenson/csv-metabase-driver/files/5672474/Sample.zip)

kindly download above file and look at csv upload issue in meta base.

**Comment by Markenson** [comment]
It's strange...

I got data when executing a native query, but no data by clicking directly on database icon. For me, this problem happens with another driver too (I've used postgres driver). Maybe it is a regression? We need test this...

Check if native query works for you.
Cheers.



![image](https://user-images.githubusercontent.com/2985140/101944320-50818f00-3bcb-11eb-8997-3aea77fd8d21.png)
![image](https://user-images.githubusercontent.com/2985140/101944448-8292f100-3bcb-11eb-915d-2fbb279d0331.png)
![image](https://user-images.githubusercontent.com/2985140/101944548-a81ffa80-3bcb-11eb-828f-10387b33bb29.png)

**Comment by Markenson** [comment]
The problem was related to have-select-privilege (https://github.com/metabase/metabase/pull/10892).

Please checkout new version at https://github.com/Markenson/csv-metabase-driver/releases/download/1.0.3/csv.metabase-driver.jar

**Comment by hireninnodel** [comment]
Thanks a lot  for Quick Response !!!

**Comment by Markenson** [comment]
;)
