### ISSUE TITLE
CSV Filename Directory not found

### ISSUE THREAD

**Issue by ljm000** [Markenson/csv-metabase-driver#7]
The file path cannot be set directly.
Only the directory path can be set.
tips:
Directory not found: /metabase/metabase-data/csv/wp.csv/
![QQ截图20201129025142](https://user-images.githubusercontent.com/12406935/100523792-163ce880-31ee-11eb-83f1-fb7f8fdecde4.jpg)

**Comment by skydance** [comment]
Hi ljm000, its not referring to csv file, but to the folder containing csv files instead.

**Comment by hydralom** [comment]
Hello, I'm having the same issue and I don't think the `Filename` placeholder is referring to the Folder name.
And the configuration by @Markenson says so too ==> https://github.com/Markenson/csv-metabase-driver/issues/1

**Comment by Markenson** [comment]
Hi! @skydance os right... Use directory instead filename. 

If directory contains multiple csv files, all of them will appear in Metabase.

**Comment by Markenson** [comment]
Hi @RaviYadu It seems same problem reported on https://github.com/Markenson/csv-metabase-driver/issues/27, right?

Can you continue handling this in these issue, please?
