### ISSUE TITLE
Tab Delimited Files

### ISSUE THREAD

**Issue by zeehasham** [Markenson/csv-metabase-driver#8]
Can we import tab delimited file using this driver? How to put the separator for tab in the textbox field?

**Comment by Markenson** [comment]
You must use \t on separator configuration.

![image](https://user-images.githubusercontent.com/2985140/101936849-da2b5f80-3bbf-11eb-84bd-dd3190a5683d.png)

**Comment by zeehasham** [comment]
Thanks

**Comment by Markenson** [comment]
;)
